import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Box, Flex, Button} from '@chakra-ui/react'
import Cover from '../public/cover.png'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cards Chakra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex boxShadow={'md'} w={'350px'} justify={'center'} fontSize={'20'} my={5} direction={'column'}>
        <Box alignSelf={'center'} w={'350px'} rounded={'15px'} overflow={'hidden'}>
          <Image src={Cover} />
        </Box>
        <Flex direction={'column'}>
          <Flex justify={'space-between'} mx={2}>
            <Box alignSelf={'center'} fontSize={'15pt'} fontWeight={'bold'}>Este es el Título</Box>
            <Box alignSelf={'center'} bg={'black'} color={'white'} rounded={'full'} p={1} fontSize={'12pt'}>$200.00 MXN</Box>
          </Flex>
          <Box ml={'2'} fontSize={'12px'} my={3}>Esta es una descripción sobre el producto a vender</Box>
          <Button variant={'outline'} w={'100px'} rounded={'full'} my={2} mx={2}>me gusta</Button>
        </Flex>
      </Flex>
    </div>
  )
}
